- name: Playbook to install and configure postgresql database in RHEL 8.4
  hosts: all
  tasks: 
  - wait_for:
      timeout: 300
    delegate_to: localhost
  
  - name: Ensure database appdb is present
    postgresql_db:
      name: test
      state: present
    become_user: postgres
