- name: playbook to create EC2 instance
  hosts: all
  tasks:
  - name: start an instance with a public IP address
    amazon.aws.ec2_instance:
      name: "Ashok Leyland"
      key_name: "ashokawskeypair"
      vpc_subnet_id: subnet-0d244753edb122d2b
      instance_type: m5d.large
      security_group: asjoksg
      network: 
        assign_public_ip: true
      image_id: ami-092b43193629811af
      tags:
        Environment: Ashok Ley
