---
- name: play to create EC2 instance
  hosts: localhost
  vars:
    aws_region: us-east-2
  tasks:
    - name:
      pip:
        name: boto3
        state: present
    - name: Task to create vpc 
      amazon.aws.ec2_vpc_net:
        name: ansible_tower_vpc
        cidr_block: 10.10.0.0/16
        region: "{{ aws_region}}"
        tenancy: default
      register: ansible_tower_vpc
    - name: Create an Internet Gateway and associate to the VPC 
      amazon.aws.ec2_vpc_igw:
        vpc_id: "{{ ansible_tower_vpc.vpc.id }}"
        region: "{{ aws_region }}"
        state: present
      register: ansible_tower_igw
    - name: Create a subnet on the VPC
      amazon.aws.ec2_vpc_subnet:
        state: present
        vpc_id: "{{ ansible_tower_vpc.vpc_id }}"
        cidr: 10.10.0.0/20
        region: "{{ aws_region }}"
      register: ansible_tower_subnet
    - name: Setup public subnet route table
      amazon.aws.ec2_vpc_route_table:
        vpc_id: "{{ ansible_tower_vpc.vpc_id }}"
        region: "{{ aws_region }}"
        subnets: "{{ ansible_tower_subnet.subnet.id }}"
        routes:
          - dest: 0.0.0.0/0
            gateway_id: "{{ ansible_tower_igw.gateway_id }}"
    - name: Task to create AWS Security group
      amazon.aws.ec2_group:
        name: ansible_tower_sg
        description: AWS Security Group for Ansible Tower Demonstration
        vpc_id: "{{ ansible_tower_vpc.vpc_id }}"
        region: "{{ aws_region }}"
        rules:
          - proto: tcp 
            ports: 22
            cidr_ip: 0.0.0.0/0
            rule_desc: allow all connections on port 22
    - name: Task to provision the RHEL 8 EC2 instance
      amazon.aws.ec2:
        region: "{{ aws_region }}"
        key_name: ansible-tower-aws-key
        instance_type: t2.medium
        image: ami-092b43193629811af
        wait: yes
        group: ansible_tower_sg
        count: 1
        vpc_subnet_id: "{{ ansible_tower_subnet.subnet.id }}"
        assign_public_ip: yes
    - name: Show rhel 8 instance details - debug output
      debug: 
        msg: "rhel8 instance is accesible at {{ ansible_tower_instance.instance[0].public_ip }}"
