---
- name: play to create EC2 instance
  hosts: localhost
  vars:
    aws_region: us-east-2
  tasks:
    - name:
      pip:
        name: boto3
        state: present
    - name: Task to create vpc 
      amazon.aws.ec2_vpc_net:
        name: ansible_tower_vpc
        cidr_block: 10.10.0.0/16
        region: "{{ aws_region}}"
        tenancy: default
      register: ansible_tower_vpc
    - name: Create an Internet Gateway and associate to the VPC 
      amazon.aws.ec2_vpc_igw:
        vpc_id: "{{ ansible_tower_vpc.vpc.id }}"
        region: "{{ aws_region }}"
        state: present
      register: ansible_tower_igw
    - name: Create a subnet on the VPC
      amazon.aws.ec2_vpc_subnet:
        state: present
        vpc_id: "{{ ansible_tower_vpc.vpc.id }}"
        cidr: 10.10.0.0/20
        region: "{{ aws_region }}"
      register: ansible_tower_subnet
    - name: Setup public subnet route table
      amazon.aws.ec2_vpc_route_table:
        vpc_id: "{{ ansible_tower_vpc.vpc.id }}"
        region: "{{ aws_region }}"
        subnets: "{{ ansible_tower_subnet.subnet.id }}"
        routes:
          - dest: 0.0.0.0/0
            gateway_id: "{{ ansible_tower_igw.gateway_id }}"
    - name: Task to create AWS Security group
      amazon.aws.ec2_group:
        name: ansible_tower_sg
        description: AWS Security Group for Ansible Tower Demonstration
        vpc_id: "{{ ansible_tower_vpc.vpc.id }}"
        region: "{{ aws_region }}"
        rules:
          - proto: tcp 
            ports: 22
            cidr_ip: 0.0.0.0/0
            rule_desc: allow all connections on port 22
    - name: Task to create key pair
      amazon.aws.ec2_key:
        name: ansible-tower-aws-key
        key_material: "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQCh4FiZbzNG7hpfhUeVCUgRbjrJC15AsoBPInQGGiZcsP+dpFuSdWKODVmJQ6+RT3USWdRy3irj7xOGGXSgCC8/+tugJftZtEqbaOxuH6ItYDrDlZgsqaUKV81BN5/PgEM45jkTwkufDqevZsluaq+XnnMF2G1Vy4iM5S20xXIgfAWzAy0ngvvmueLmctdZHQFVocPfnp3kdeFRkbS3Z9i5RyQtHlsYoNI9c1UXjPXQvb49HxDldFj8wvP7EuKHuef1UU9yL2NN6C0eD0INWoPH1tC1hEkE8qkqmUthzeAIvILDnuZmiYmXHkKY/iGwEp38vdgLVjowXzAI71SdkEOR83IP+TcgBaPYAY1PYnkearpzYiPm3+dCJwEplgG5mK+jq3++oqrh5yOtaUVNNMKAGntV/BpFkD91Dk7OWCUuselOxrEOH6qoqRF4LXBXH9My6YE0LxTkUNK6bvl4I5XMzb9axU4oXqOeB6Q/38IP5CZKSWY/gpEsV4TQqlEL0u8= Nivedv@fedora"
        region: "{{ aws_region }}"
    - name: Task to provision the RHEL 8 EC2 instance
      amazon.aws.ec2:
        region: "{{ aws_region }}"
        key_name: ansible-tower-aws-key
        instance_type: t2.medium
        image: ami-0fecef330e60167c1
        wait: yes
        group: ansible_tower_sg
        instance_tags:
          Name: RHEL
        count: 1
        vpc_subnet_id: "{{ ansible_tower_subnet.subnet.id }}"
        assign_public_ip: yes
      register: ansible_tower_instance_rhel
    - name: Show rhel 8 instance details - debug output
      debug: 
        msg: "rhel8 instance is accesible at {{ ansible_tower_instance_rhel }}"
    - name: Task to provision the Windows Server 2019 EC2 instance
      amazon.aws.ec2:
        region: "{{ aws_region }}"
        key_name: ansible-tower-aws-key
        instance_type: t2.medium
        image: ami-0d72555523e18b6d7
        wait: yes
        group: ansible_tower_sg
        instance_tags:
          Name: Windows
        count: 1
        vpc_subnet_id: "{{ ansible_tower_subnet.subnet.id }}"
        assign_public_ip: yes
      register: ansible_tower_instance_windows
    - name: Show windows instance details - debug output
      debug: 
        msg: "windows instance is accesible at {{ ansible_tower_instance_windows }}"

