#Note: For this playbook to work ansible requires PyVmomi package to be installed on the vmware vcenter host.
- name: VMWare Automation 
  hosts: all
  tasks:
    - name: Create a virtual machine on given ESXi hostname
  		vmware_guest:
    		hostname: asbcolvcs01.corp.suth.com
    		username: sgl\chavikas1
    		password: "{{ vcenter_password }}"
    		validate_certs: no
          #	folder: /DC1/vm/
    		name: asbgenosh02
    		state: poweredon
    		guest_id: rhel8_64Guest
    # This is hostname of particular ESXi server on which user wants VM to be deployed
    		esxi_hostname: asbcolhfx13.corp.suth.com
    		disk:
    		- size_gb: 10
      		type: thin
      		datastore: ASBCOLVSI01-DS02
    		hardware:
      		memory_mb: 2048
      		num_cpus: 4
      		scsi: paravirtual
    		networks:
    		- name: VM Network
          #	mac: aa:bb:dd:aa:00:14
      		ip: 10.61.84.191
      		netmask: 255.255.252.0
      		device_type: vmxnet3
    		wait_for_ip_address: yes
  		delegate_to: localhost
  		register: deploy_vm
    - name: Debug if the VM was deployed successfully
      debug:
        var: deploy_vm.instance.ipv4
