- name: Test Vmware automation
  hosts: localhost #<ip ofcontroler host>
  tasks:
    - name: Build a list of all the clusters
      vmware.vmware_rest.vcenter_cluster_info:
      register: all_the_clusters
    - name: Get information regarding vcenter host
      vmware.vmware_rest.vcenter_cluster_info:
        cluster: '{{ all_the_clusters.value[0].cluster }}'
      register: my_cluster_info
    - debug: var=my_cluster_info
    - name: Create a VM
      vmware.vmware_rest.vcenter_vm:
        placement:
          cluster: '{{ my_cluster_info.id }}'
          datastore: ASBCOLVSI01-DS02
            #	folder: '{{ my_virtual_machine_folder.folder }}'
            #resource_pool: present
        name: asbgenosh02
        guest_OS: RHEL_8_64
        cpu:
          count: 4
        memory:
          hot_add_enabled: true
          size_MiB: 2048
        disks:
          - type: SATA
            new_vmdk:
              name: test1
              capacity: 12000000000
      register: my_vm
    - name: Debug info regarding VM
      debug: var=my_vm.instance.ipv4
