- name: Create VM using templates
  hosts: localhost
  tasks:
  - name: Create a virtual machine on given ESXi hostname using templates
    community.vmware.vmware_guest:
      folder: "{{ vcenter_folder }}"
      datacenter: "{{ vcenter_datacenter }}"
      name: "{{ vm_name }}"
      state: poweredon
      template: "{{ vcenter_template }}"
      disk:
      - size_gb: 40
        type: thin
        datastore: "{{ vcenter_datastore }}"
      hardware:
        memory_mb: 2048
        num_cpus: 4
        scsi: paravirtual
      validate_certs: false
    delegate_to: localhost
    register: deploy_vm

  - name: Debug the created VM
    debug:
      var: deploy_vm
