- name: Testing community vmware
  hosts: localhost
  tasks:
  - name: Create a virtual machine on given ESXi hostname
    community.vmware.vmware_guest:
      hostname: 
      username: 
      password: 
      folder: test
      datacenter: prod-dc
      name: test_vm_0001
      state: poweredon
      template: ajawarka-rhel8
    # This is hostname of particular ESXi server on which user wants VM to be deployed
      disk:
      - size_gb: 40
        type: thin
        datastore: Datastore
      hardware:
        memory_mb: 2048
        num_cpus: 4
        scsi: paravirtual
#    	networks:
#    	- name: VM Network
#      	ip: 10.10.10.100
#      	netmask: 255.255.255.0
#      	device_type: vmxnet3
      validate_certs: false
    delegate_to: localhost
    register: deploy_vm
